// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pluralsh/kubernetes-agent/pkg/module/reverse_tunnel/tunnel (interfaces: DataCallback,Querier,Tracker)
//
// Generated by this command:
//
//	mockgen -typed -self_package github.com/pluralsh/kubernetes-agent/pkg/module/reverse_tunnel/tunnel -destination mock_for_test.go -package tunnel github.com/pluralsh/kubernetes-agent/pkg/module/reverse_tunnel/tunnel DataCallback,Querier,Tracker
//
// Package tunnel is a generated GoMock package.
package tunnel

import (
	context "context"
	reflect "reflect"
	time "time"

	prototool "github.com/pluralsh/kubernetes-agent/pkg/tool/prototool"
	gomock "go.uber.org/mock/gomock"
	status "google.golang.org/genproto/googleapis/rpc/status"
)

// MockDataCallback is a mock of DataCallback interface.
type MockDataCallback struct {
	ctrl     *gomock.Controller
	recorder *MockDataCallbackMockRecorder
}

// MockDataCallbackMockRecorder is the mock recorder for MockDataCallback.
type MockDataCallbackMockRecorder struct {
	mock *MockDataCallback
}

// NewMockDataCallback creates a new mock instance.
func NewMockDataCallback(ctrl *gomock.Controller) *MockDataCallback {
	mock := &MockDataCallback{ctrl: ctrl}
	mock.recorder = &MockDataCallbackMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataCallback) EXPECT() *MockDataCallbackMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockDataCallback) Error(arg0 *status.Status) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockDataCallbackMockRecorder) Error(arg0 any) *DataCallbackErrorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockDataCallback)(nil).Error), arg0)
	return &DataCallbackErrorCall{Call: call}
}

// DataCallbackErrorCall wrap *gomock.Call
type DataCallbackErrorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *DataCallbackErrorCall) Return(arg0 error) *DataCallbackErrorCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *DataCallbackErrorCall) Do(f func(*status.Status) error) *DataCallbackErrorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *DataCallbackErrorCall) DoAndReturn(f func(*status.Status) error) *DataCallbackErrorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Header mocks base method.
func (m *MockDataCallback) Header(arg0 map[string]*prototool.Values) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Header indicates an expected call of Header.
func (mr *MockDataCallbackMockRecorder) Header(arg0 any) *DataCallbackHeaderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockDataCallback)(nil).Header), arg0)
	return &DataCallbackHeaderCall{Call: call}
}

// DataCallbackHeaderCall wrap *gomock.Call
type DataCallbackHeaderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *DataCallbackHeaderCall) Return(arg0 error) *DataCallbackHeaderCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *DataCallbackHeaderCall) Do(f func(map[string]*prototool.Values) error) *DataCallbackHeaderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *DataCallbackHeaderCall) DoAndReturn(f func(map[string]*prototool.Values) error) *DataCallbackHeaderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Message mocks base method.
func (m *MockDataCallback) Message(arg0 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Message", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Message indicates an expected call of Message.
func (mr *MockDataCallbackMockRecorder) Message(arg0 any) *DataCallbackMessageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Message", reflect.TypeOf((*MockDataCallback)(nil).Message), arg0)
	return &DataCallbackMessageCall{Call: call}
}

// DataCallbackMessageCall wrap *gomock.Call
type DataCallbackMessageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *DataCallbackMessageCall) Return(arg0 error) *DataCallbackMessageCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *DataCallbackMessageCall) Do(f func([]byte) error) *DataCallbackMessageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *DataCallbackMessageCall) DoAndReturn(f func([]byte) error) *DataCallbackMessageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Trailer mocks base method.
func (m *MockDataCallback) Trailer(arg0 map[string]*prototool.Values) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockDataCallbackMockRecorder) Trailer(arg0 any) *DataCallbackTrailerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockDataCallback)(nil).Trailer), arg0)
	return &DataCallbackTrailerCall{Call: call}
}

// DataCallbackTrailerCall wrap *gomock.Call
type DataCallbackTrailerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *DataCallbackTrailerCall) Return(arg0 error) *DataCallbackTrailerCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *DataCallbackTrailerCall) Do(f func(map[string]*prototool.Values) error) *DataCallbackTrailerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *DataCallbackTrailerCall) DoAndReturn(f func(map[string]*prototool.Values) error) *DataCallbackTrailerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// KasUrlsByAgentId mocks base method.
func (m *MockQuerier) KasUrlsByAgentId(arg0 context.Context, arg1 int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KasUrlsByAgentId", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KasUrlsByAgentId indicates an expected call of KasUrlsByAgentId.
func (mr *MockQuerierMockRecorder) KasUrlsByAgentId(arg0, arg1 any) *QuerierKasUrlsByAgentIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KasUrlsByAgentId", reflect.TypeOf((*MockQuerier)(nil).KasUrlsByAgentId), arg0, arg1)
	return &QuerierKasUrlsByAgentIdCall{Call: call}
}

// QuerierKasUrlsByAgentIdCall wrap *gomock.Call
type QuerierKasUrlsByAgentIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *QuerierKasUrlsByAgentIdCall) Return(arg0 []string, arg1 error) *QuerierKasUrlsByAgentIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *QuerierKasUrlsByAgentIdCall) Do(f func(context.Context, int64) ([]string, error)) *QuerierKasUrlsByAgentIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *QuerierKasUrlsByAgentIdCall) DoAndReturn(f func(context.Context, int64) ([]string, error)) *QuerierKasUrlsByAgentIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockTracker is a mock of Tracker interface.
type MockTracker struct {
	ctrl     *gomock.Controller
	recorder *MockTrackerMockRecorder
}

// MockTrackerMockRecorder is the mock recorder for MockTracker.
type MockTrackerMockRecorder struct {
	mock *MockTracker
}

// NewMockTracker creates a new mock instance.
func NewMockTracker(ctrl *gomock.Controller) *MockTracker {
	mock := &MockTracker{ctrl: ctrl}
	mock.recorder = &MockTrackerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTracker) EXPECT() *MockTrackerMockRecorder {
	return m.recorder
}

// KasUrlsByAgentId mocks base method.
func (m *MockTracker) KasUrlsByAgentId(arg0 context.Context, arg1 int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KasUrlsByAgentId", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KasUrlsByAgentId indicates an expected call of KasUrlsByAgentId.
func (mr *MockTrackerMockRecorder) KasUrlsByAgentId(arg0, arg1 any) *TrackerKasUrlsByAgentIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KasUrlsByAgentId", reflect.TypeOf((*MockTracker)(nil).KasUrlsByAgentId), arg0, arg1)
	return &TrackerKasUrlsByAgentIdCall{Call: call}
}

// TrackerKasUrlsByAgentIdCall wrap *gomock.Call
type TrackerKasUrlsByAgentIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *TrackerKasUrlsByAgentIdCall) Return(arg0 []string, arg1 error) *TrackerKasUrlsByAgentIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *TrackerKasUrlsByAgentIdCall) Do(f func(context.Context, int64) ([]string, error)) *TrackerKasUrlsByAgentIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *TrackerKasUrlsByAgentIdCall) DoAndReturn(f func(context.Context, int64) ([]string, error)) *TrackerKasUrlsByAgentIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Refresh mocks base method.
func (m *MockTracker) Refresh(arg0 context.Context, arg1 time.Duration, arg2 ...int64) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Refresh", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Refresh indicates an expected call of Refresh.
func (mr *MockTrackerMockRecorder) Refresh(arg0, arg1 any, arg2 ...any) *TrackerRefreshCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockTracker)(nil).Refresh), varargs...)
	return &TrackerRefreshCall{Call: call}
}

// TrackerRefreshCall wrap *gomock.Call
type TrackerRefreshCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *TrackerRefreshCall) Return(arg0 error) *TrackerRefreshCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *TrackerRefreshCall) Do(f func(context.Context, time.Duration, ...int64) error) *TrackerRefreshCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *TrackerRefreshCall) DoAndReturn(f func(context.Context, time.Duration, ...int64) error) *TrackerRefreshCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RegisterTunnel mocks base method.
func (m *MockTracker) RegisterTunnel(arg0 context.Context, arg1 time.Duration, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterTunnel", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterTunnel indicates an expected call of RegisterTunnel.
func (mr *MockTrackerMockRecorder) RegisterTunnel(arg0, arg1, arg2 any) *TrackerRegisterTunnelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterTunnel", reflect.TypeOf((*MockTracker)(nil).RegisterTunnel), arg0, arg1, arg2)
	return &TrackerRegisterTunnelCall{Call: call}
}

// TrackerRegisterTunnelCall wrap *gomock.Call
type TrackerRegisterTunnelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *TrackerRegisterTunnelCall) Return(arg0 error) *TrackerRegisterTunnelCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *TrackerRegisterTunnelCall) Do(f func(context.Context, time.Duration, int64) error) *TrackerRegisterTunnelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *TrackerRegisterTunnelCall) DoAndReturn(f func(context.Context, time.Duration, int64) error) *TrackerRegisterTunnelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UnregisterTunnel mocks base method.
func (m *MockTracker) UnregisterTunnel(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnregisterTunnel", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnregisterTunnel indicates an expected call of UnregisterTunnel.
func (mr *MockTrackerMockRecorder) UnregisterTunnel(arg0, arg1 any) *TrackerUnregisterTunnelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterTunnel", reflect.TypeOf((*MockTracker)(nil).UnregisterTunnel), arg0, arg1)
	return &TrackerUnregisterTunnelCall{Call: call}
}

// TrackerUnregisterTunnelCall wrap *gomock.Call
type TrackerUnregisterTunnelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *TrackerUnregisterTunnelCall) Return(arg0 error) *TrackerUnregisterTunnelCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *TrackerUnregisterTunnelCall) Do(f func(context.Context, int64) error) *TrackerUnregisterTunnelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *TrackerUnregisterTunnelCall) DoAndReturn(f func(context.Context, int64) error) *TrackerUnregisterTunnelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
