{{- $podAnnotations := (list $ .Values.podAnnotations) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  # NOTE: the `-v1` suffix was introduced as an epoch version to be able
  # to gracefully recreate the deployment in case there is no upgrade
  # path otherwise, e.g. when changing an immutable field.
  # see https://gitlab.com/gitlab-org/charts/gitlab-agent/-/issues/38 for ctx
  name: {{ include "agentk.fullname" . | trunc 60 }}-v1
  labels:
    {{- include "agentk.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "agentk.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "agentk.annotations" $podAnnotations | indent 8 }}
      labels:
        {{- include "agentk.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{-   toYaml . | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "agentk.serviceAccountName" . }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          terminationMessagePolicy: {{ .Values.terminationMessagePolicy }}
          args:
            - --token-file=/etc/agentk/secrets/token
            - --kas-address={{ .Values.config.kasAddress }}
            {{- if .Values.config.caCert }}
            - --ca-cert-file=/etc/agentk/config/ca.crt
            {{- end }}
            {{- if .Values.config.kasHeaders }}
            {{- range .Values.config.kasHeaders }}
            - --kas-header
            - {{ . | quote }}
            {{- end }}
            {{- end }}
            {{- range .Values.extraArgs }}
            - {{ . }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
               fieldRef:
                 fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVICE_ACCOUNT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          {{- if .Values.extraEnv }}
            {{- toYaml .Values.extraEnv | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: service-account-token-volume
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              readOnly: true
            {{- if or .Values.config.token .Values.config.secretName }}
            - name: secret-volume
              mountPath: /etc/agentk/secrets
              readOnly: true
            {{- end }}
            {{- if .Values.config.caCert }}
            - name: config-volume
              mountPath: /etc/agentk/config
              readOnly: true
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: service-account-token-volume
          projected:
            defaultMode: 0444
            sources:
            - configMap:
                name: kube-root-ca.crt
            - downwardAPI:
                items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
            - serviceAccountToken:
                expirationSeconds: 3600
                path: token
        {{- if or .Values.config.token .Values.config.secretName }}
        - name: secret-volume
          secret:
            defaultMode: 0444
            secretName: {{ include "agentk.secretName" . }}
        {{- end }}
        {{- if .Values.config.caCert }}
        - name: config-volume
          configMap:
            defaultMode: 0444
            name: {{ include "agentk.fullname" . }}
        {{- end }}
        {{- if .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hostAliases  }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
