// Code generated by MockGen. DO NOT EDIT.
// Source: ../../redistool/expiring_hash_api.go
//
// Generated by this command:
//
//	mockgen -source ../../redistool/expiring_hash_api.go -destination expiring_hash_api.go -package mock_redis
//
// Package mock_redis is a generated GoMock package.
package mock_redis

import (
	context "context"
	reflect "reflect"

	redistool "gitlab.com/gitlab-org/cluster-integration/gitlab-agent/v16/internal/tool/redistool"
	gomock "go.uber.org/mock/gomock"
)

// MockExpiringHashApi is a mock of ExpiringHashApi interface.
type MockExpiringHashApi[K1 any, K2 any] struct {
	ctrl     *gomock.Controller
	recorder *MockExpiringHashApiMockRecorder[K1, K2]
}

// MockExpiringHashApiMockRecorder is the mock recorder for MockExpiringHashApi.
type MockExpiringHashApiMockRecorder[K1 any, K2 any] struct {
	mock *MockExpiringHashApi[K1, K2]
}

// NewMockExpiringHashApi creates a new mock instance.
func NewMockExpiringHashApi[K1 any, K2 any](ctrl *gomock.Controller) *MockExpiringHashApi[K1, K2] {
	mock := &MockExpiringHashApi[K1, K2]{ctrl: ctrl}
	mock.recorder = &MockExpiringHashApiMockRecorder[K1, K2]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExpiringHashApi[K1, K2]) EXPECT() *MockExpiringHashApiMockRecorder[K1, K2] {
	return m.recorder
}

// Scan mocks base method.
func (m *MockExpiringHashApi[K1, K2]) Scan(ctx context.Context, key K1, cb redistool.ScanCallback) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scan", ctx, key, cb)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Scan indicates an expected call of Scan.
func (mr *MockExpiringHashApiMockRecorder[K1, K2]) Scan(ctx, key, cb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockExpiringHashApi[K1, K2])(nil).Scan), ctx, key, cb)
}

// SetBuilder mocks base method.
func (m *MockExpiringHashApi[K1, K2]) SetBuilder() redistool.SetBuilder[K1, K2] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBuilder")
	ret0, _ := ret[0].(redistool.SetBuilder[K1, K2])
	return ret0
}

// SetBuilder indicates an expected call of SetBuilder.
func (mr *MockExpiringHashApiMockRecorder[K1, K2]) SetBuilder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBuilder", reflect.TypeOf((*MockExpiringHashApi[K1, K2])(nil).SetBuilder))
}

// Unset mocks base method.
func (m *MockExpiringHashApi[K1, K2]) Unset(ctx context.Context, key K1, hashKey K2) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unset", ctx, key, hashKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unset indicates an expected call of Unset.
func (mr *MockExpiringHashApiMockRecorder[K1, K2]) Unset(ctx, key, hashKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unset", reflect.TypeOf((*MockExpiringHashApi[K1, K2])(nil).Unset), ctx, key, hashKey)
}
